name: "dbt_orchestration"
version: "1.0.0"
config-version: 2

profile: "bigquery"

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  dbt_orchestration:
    iowa_liquor_sales:
      schema: iowa_liquor_sales
      materialized: view
