# deploy and test dbt models on pushes to main
name: development

on:
  # Trigger on pushes to the main branch
  push:
    branches: [ main ]
  # Allows the workflow to be run manually from the actions tab
  workflow_dispatch:

jobs:
  rundbt:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      # Check-out repository
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create virtual environment
        run: |
          python -m venv env
          .\env\Scripts\activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          dbt deps
      - name: Run a one-line script
        run: echo Hello, world!
