# deploy and test dbt models on pushes to main
name: development

on:
  # Trigger on pushes to the main branch
  push:
    branches: [ main ]
  # Allows the workflow to be run manually from the actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Check-out repository
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
